### ISSUE TITLE
Shrink headlines slightly at mobile screen sizes

### ISSUE THREAD

**Issue by jayperryworks** [biveeprojects/carmine-teaser#5]
Not a serious issue, but the headlines are little big on small screens and it creates some awkward wrapping. I suggest using media queries to adjust the font size for various screen sizes.

![img_1070](https://cloud.githubusercontent.com/assets/1044536/24466704/c816829a-147f-11e7-9619-9a582a08ebed.PNG)

![img_1071](https://cloud.githubusercontent.com/assets/1044536/24466708/ce5294b4-147f-11e7-8267-445047fd22e5.PNG)

**Comment by hcline** [comment]
@jayperryworks I think I edited this in my latest commit but not sure if it was correct
