### ISSUE TITLE
Add webfonts and @font-face declarations

### ISSUE THREAD

**Issue by jayperryworks** [biveeprojects/carmine-teaser#8]
Looks like Lato is only displaying when locally installed - we just need to add the webfont files to the source, and set up the CSS declarations.

It's degrading gracefully to Arial/Helvetica though.

**Comment by sschafft** [comment]
@jayperryworks - I think this is done yea?

**Comment by jayperryworks** [comment]
@sschafft yeah, I just wanted to confirm webfonts were working on the server before calling it. if you can deploy I can double check in various browsers.

**Comment by sschafft** [comment]
Pushed - test away @jayperryworks
